/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PENJUALAN;

//import static reparasi.buang.PEMBELIAN.jTable1;
import dayattt.koneksi;
import dayattt.masukan_pelanggan;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import reparasi.uubah;

/**
 *
 * @author Acer
 */
public final class JPENJUALAN extends javax.swing.JPanel {

    private DefaultTableModel pelanggan;
    private DefaultTableModel mdl;
    private TablePenjualan TRSNK;

    private List<ppenjualan> penjualans;
    private ppenjualan penjualan;
    int count, jml_awal;
    String GANTI;
    String NO;

    /**
     * Creates new form JPENJUALAN
     */
    public JPENJUALAN() {
        initComponents();

        pelanggan = new DefaultTableModel();
        mdl = new DefaultTableModel();

        jTable3.setModel(mdl);
        jTable1.setModel(pelanggan);
        pelanggan.addColumn("ID PELANGGAN");
        pelanggan.addColumn("NAMA");
        pelanggan.addColumn("NOHP");

        mdl.addColumn("ID BARANG");
        mdl.addColumn("NAMA BARANG");
        mdl.addColumn("JUMLAH");
        mdl.addColumn("HARGA");
        mdl.addColumn("GARANSI");
        mdl.addColumn("WAKTU");
        mdl.addColumn("KETERANGAN");

        TRSNK = new TablePenjualan();
        TABELTRANSAKSI.setModel(TRSNK);
        penjualans = new ArrayList<ppenjualan>();

        getDataPembelian();
        loadData();
        TABELbarang();

        TABELTRANSAKSI.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent lse) {
                int row = TABELTRANSAKSI.getSelectedRow();
                if (row != -1) {
                    penjualan = TRSNK.get(row);
                    NAMA.setText(penjualan.getNAMAPELANGGAN());
                    IDPELANGGAN.setText(penjualan.getIDPELANGGAN());
                    NAMABRANG.setText(penjualan.getNAMABARANG());
                    idbarang.setText(penjualan.getIDBARANG());
                    JUMLAH.setText(penjualan.getJUMLAH());
                    WAKTU.setDate(penjualan.getWAKTU());
                    HARGA.setText(penjualan.getHARGA());
                    totalharga.setText(penjualan.getTOTAL());
                    BAYAR.setText(penjualan.getBAYAR());
                    KEMBALIAN.setText(penjualan.getKEMBALIAN());
                    GARANSI.setText(penjualan.getGARANSI());
                    KODE.setText(penjualan.getCODE());
//                    OLEH.setText(penjualan.getUSER());

                }
            }

        });
    }

    public void loadData() {
        penjualans = KoneksiPenjualan.getPenjualanDAO().getAll();
        TRSNK.setData(penjualans);
    }

    private void clear() {

        NAMA.setText("");
        NAMABRANG.setText("");
        JUMLAH.setText("");
        totalharga.setText("");
        GARANSI.setText("");
        WAKTU.setDate(null);
        HARGA.setText("");
        KODE.setText("");
        KEMBALIAN.setText("");
        BAYAR.setText("");
        IDPELANGGAN.setText("");
        idbarang.setText("");
//        OLEH.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private class TablePenjualan extends AbstractTableModel {

        private List<ppenjualan> list = new ArrayList();

        public void setData(List<ppenjualan> list) {
            this.list = list;
            fireTableDataChanged();
        }

        public int getRowCount() {
            return list.size();
        }

        public int getColumnCount() {
            return 13;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return list.get(rowIndex).getIDPELANGGAN();
                case 1:
                    return list.get(rowIndex).getNAMAPELANGGAN();
                case 2:
                    return list.get(rowIndex).getIDBARANG();
                case 3:
                    return list.get(rowIndex).getNAMABARANG();
                case 4:
                    return list.get(rowIndex).getJUMLAH();
                case 5:
                    return list.get(rowIndex).getWAKTU();
                case 6:
                    return list.get(rowIndex).getHARGA();
                case 7:
                    return list.get(rowIndex).getTOTAL();
                case 8:
                    return list.get(rowIndex).getBAYAR();
                case 9:
                    return list.get(rowIndex).getKEMBALIAN();
                case 10:
                    return list.get(rowIndex).getGARANSI();
                case 11:
                    return list.get(rowIndex).getCODE();
                case 12:
                    return list.get(rowIndex).getUSER();
                default:
                    return null;
            }
        }

        @Override
        public String getColumnName(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return "ID PELANGGAN";
                case 1:
                    return "NAMA PELANGGAN";
                case 2:
                    return "ID BARANG";
                case 3:
                    return "NAMA BARANG";
                case 4:
                    return "JUMLAH";
                case 5:
                    return "WAKTU";
                case 6:
                    return "HARGA";
                case 7:
                    return "TOTAL";
                case 8:
                    return "BAYAR";
                case 9:
                    return "KEMBALIAN";
                case 10:
                    return "GARANSI";
                case 11:
                    return "KODE";
                case 12:
                    return "USER";
                default:
                    return null;
            }
        }

        public void insertTable(ppenjualan ubah) {
            list.add(ubah);
            fireTableDataChanged();
        }

        public void updateTable(ppenjualan ubah, int rowIndex) {
            list.set(rowIndex, ubah);
            fireTableDataChanged();
        }

        public ppenjualan get(int rowIndex) {
            return list.get(rowIndex);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NAMA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NAMABRANG = new javax.swing.JTextField();
        JUMLAH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GARANSI = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        WAKTU = new com.toedter.calendar.JDateChooser();
        HARGA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalharga = new javax.swing.JLabel();
        TEXTKODEE = new javax.swing.JLabel();
        KODE1 = new javax.swing.JLabel();
        KODE = new javax.swing.JTextField();
        KEMBALIAN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        idbarang = new javax.swing.JTextField();
        IDPELANGGAN = new javax.swing.JTextField();
        BAYAR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABELTRANSAKSI = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 0, 51));

        jPanel1.setBackground(new java.awt.Color(192, 92, 126));

        jPanel2.setBackground(new java.awt.Color(243, 130, 111));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAMA.setEnabled(false);
        jPanel2.add(NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NAMA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 109, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("BARANG YANG DI BELI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        NAMABRANG.setEnabled(false);
        jPanel2.add(NAMABRANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 190, -1));

        JUMLAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUMLAHActionPerformed(evt);
            }
        });
        JUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JUMLAHKeyReleased(evt);
            }
        });
        jPanel2.add(JUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 220, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("JUMLAH");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 109, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("TANGGAL PEMBELIAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("GARANSI");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 109, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("RP.");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        GARANSI.setEnabled(false);
        jPanel2.add(GARANSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 220, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("HARGA ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 109, -1));

        WAKTU.setMaxSelectableDate(new java.util.Date(253370797281000L));
        jPanel2.add(WAKTU, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, -1));

        HARGA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HARGA.setText("0");
        jPanel2.add(HARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("RP.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        totalharga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalharga.setText("0");
        jPanel2.add(totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, -1));

        TEXTKODEE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TEXTKODEE.setText("KODE");
        jPanel2.add(TEXTKODEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 80, -1));

        KODE1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KODE1.setText("USER");
        jPanel2.add(KODE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, -1));

        KODE.setEnabled(false);
        jPanel2.add(KODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 220, -1));

        OLEH.setEnabled(false);
        jPanel2.add(OLEH, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, -1));

        KEMBALIAN.setEnabled(false);
        jPanel2.add(KEMBALIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("KEMBALIAN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 109, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("TOTAL HARGA");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 109, 20));

        idbarang.setEnabled(false);
        jPanel2.add(idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 30, -1));

        IDPELANGGAN.setEnabled(false);
        jPanel2.add(IDPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 30, -1));

        BAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BAYARKeyReleased(evt);
            }
        });
        jPanel2.add(BAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("BAYAR");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 109, -1));

        jPanel3.setBackground(new java.awt.Color(243, 130, 111));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("PELANGGAN"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CARI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("BARANG"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 366, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 185, 97));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_print_26px.png"))); // NOI18N
        jButton6.setText("CETAK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_settings_32px.png"))); // NOI18N
        jButton7.setText("UBAH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_save_32px.png"))); // NOI18N
        jButton8.setText("SIMPAN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_clear_symbol_26px.png"))); // NOI18N
        jButton9.setText("HAPUS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("PEMBELIAN");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("BELI"));

        TABELTRANSAKSI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABELTRANSAKSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELTRANSAKSIMouseClicked(evt);
            }
        });
        TABELTRANSAKSI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TABELTRANSAKSIKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TABELTRANSAKSI);

        jButton5.setText("CARI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(517, 517, 517))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField9)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JUMLAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUMLAHActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JUMLAHActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:

        int pilih = jTable1.getSelectedRow();
        if (pilih == -1) {
            return;
        }
        String id = (String) jTable1.getValueAt(pilih, 0);
        IDPELANGGAN.setText(id);
        String nama = (String) jTable1.getValueAt(pilih, 1);
        NAMA.setText(nama);
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dMMyyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        KODE.setText(id + "PB" + tanggal);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID BARANG");
        tabelnyo.addColumn("NAMA BARANG");
        tabelnyo.addColumn("JUMLAH");
        tabelnyo.addColumn("HARGA");
        tabelnyo.addColumn("GARANSI");
        tabelnyo.addColumn("WAKTU");
        tabelnyo.addColumn("KETERANGAN");

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM barangdb where ID_BARANG like '%" + jTextField8.getText() + "%' OR namabarang like '%" + jTextField8.getText() + "%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),});
            }
            jTable3.setModel(tabelnyo);

        } catch (SQLException e) {
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int pilih = jTable3.getSelectedRow();
        if (pilih == -1) {
            return;
        }

        String ngambilID = (String) jTable3.getValueAt(pilih, 0);
        idbarang.setText(ngambilID);
        String namabarang = (String) jTable3.getValueAt(pilih, 1);
        NAMABRANG.setText(namabarang);
//        String STOK = (String) jTable3.getValueAt(pilih, 2);
//        stok.setText(STOK);
        String nama = (String) jTable3.getValueAt(pilih, 3);
        HARGA.setText(nama);
        String garansi = (String) jTable3.getValueAt(pilih, 4);
        GARANSI.setText(garansi);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
{
        penjualan = new ppenjualan();
        penjualan.setIDPELANGGAN(IDPELANGGAN.getText());
        penjualan.setNAMAPELANGGAN(NAMA.getText());
        penjualan.setIDBARANG(idbarang.getText());
        penjualan.setNAMABARANG(NAMABRANG.getText());
        penjualan.setJUMLAH(JUMLAH.getText());
        penjualan.setWAKTU(WAKTU.getDate());
        penjualan.setHARGA(HARGA.getText());
        penjualan.setTOTAL(totalharga.getText());
        penjualan.setBAYAR(BAYAR.getText());
        penjualan.setKEMBALIAN(KEMBALIAN.getText());
        penjualan.setGARANSI(GARANSI.getText());
        penjualan.setCODE(KODE.getText());
        penjualan.setUSER(OLEH.getText());
//        if (sPROSES.isSelected()){
//            ubah.setSTATUS("proses");
//        }else{
//            ubah.setSTATUS("di terima pemilik");
//        }
        KoneksiPenjualan.getPenjualanDAO().save(penjualan);
         TABELbarang();
        loadData();
        CARIData();
//        clear();
}
//        GANTI = "TAMBAH";
//
//        try {
//            if (Integer.parseInt(JUMLAH.getText()) <= CEKTOCK()) {
//                UPDATESTOCK(GANTI);
////                MASUKANTRANSAKSI();
////                TAMPILTRANSAKSI();
////                TABELbarang();
//            } else {
//                JOptionPane.showMessageDialog(null, "STOK BARANG HABIS");
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(JPENJUALAN.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus Data?","Hapus Data",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
        KoneksiPenjualan.getPenjualanDAO().delete(penjualan);
        TABELbarang();
        loadData();
        CARIData();
        clear();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CARIData();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void CARIData() {
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID PELANGGAN");
        tabelnyo.addColumn("NAMAPELANGGAN");
        tabelnyo.addColumn("ID BARANG");
        tabelnyo.addColumn("NAMA BARANG");
        tabelnyo.addColumn("JUMLAH");
        tabelnyo.addColumn("WAKTU");
        tabelnyo.addColumn("HARGA");
        tabelnyo.addColumn("TOTAL");
        tabelnyo.addColumn("GARANSI");
        tabelnyo.addColumn("CODE");
        tabelnyo.addColumn("USER");

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM ((pembelian INNER JOIN pelanggan ON pembelian.ID_PELANGGAN=pelanggan.ID_PELANGGAN) INNER JOIN barangdb ON pembelian.ID_BARANG = barangdb.ID_BARANG) where KODE like '%" + jTextField9.getText() + "%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(2),
                    rs.getString(12),
                    rs.getString(3),
                    rs.getString(15),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)

                });
            }
            TABELTRANSAKSI.setModel(tabelnyo);

        } catch (SQLException e) {
        }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Mengubah Data ??","Ubah Data",JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){        // TODO add your handling code here:

//        penjualan = new ppenjualan();
        penjualan.setIDPELANGGAN(IDPELANGGAN.getText());
//        penjualan.setNAMAPELANGGAN(NAMA.getText());
        penjualan.setIDBARANG(idbarang.getText());
//        penjualan.setNAMABARANG(NAMABRANG.getText());
        penjualan.setJUMLAH(JUMLAH.getText());
        penjualan.setWAKTU(WAKTU.getDate());
        penjualan.setHARGA(HARGA.getText());
        penjualan.setTOTAL(totalharga.getText());
        penjualan.setBAYAR(BAYAR.getText());
        penjualan.setKEMBALIAN(KEMBALIAN.getText());
        penjualan.setGARANSI(GARANSI.getText());
        penjualan.setCODE(KODE.getText());
        penjualan.setUSER(OLEH.getText());
//        if (sPROSES.isSelected()){
//            ubah.setSTATUS("proses");
//        }else{
//            ubah.setSTATUS("di terima pemilik");
//        }
        KoneksiPenjualan.getPenjualanDAO().update(penjualan);
        loadData();
        CARIData();
        clear();
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/datareparasi";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {

                String report = ("D:\\mencoba\\dayattt\\src\\cetak\\cetaknotabeli\\report2.jrxml");

                HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("kode", KODE.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt) {
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void TABELTRANSAKSIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABELTRANSAKSIKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TABELTRANSAKSIKeyPressed

    private void TABELTRANSAKSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELTRANSAKSIMouseClicked


    }//GEN-LAST:event_TABELTRANSAKSIMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        caripelanggan();

    }//GEN-LAST:event_jButton1ActionPerformed
    public void caripelanggan() {

        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID PELANGGAN");
        tabelnyo.addColumn("NAMA");
        tabelnyo.addColumn("NOHP");

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM pelanggan where ID_PELANGGAN like '%" + jTextField5.getText() + "%' OR nama like '%" + jTextField5.getText() + "%' OR nohp like '%" + jTextField5.getText() + "%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),});
            }
            jTable1.setModel(tabelnyo);

        } catch (SQLException e) {
        }

    }
    private void JUMLAHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JUMLAHKeyReleased
        // TODO add your handling code here:
        int jumlah, harga, ttlbayar;

        try {
           
            harga = Integer.valueOf(HARGA.getText());
            jumlah = Integer.valueOf(JUMLAH.getText());
            ttlbayar = harga * jumlah;
            totalharga.setText(String.valueOf(ttlbayar).trim());
            //         getData();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_JUMLAHKeyReleased

    private void BAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BAYARKeyReleased
        // TODO add your handling code here:
        int bayar, TOTAL, kembalian;

        try {
            //Kode kamu disini
            TOTAL = Integer.valueOf(totalharga.getText());
            bayar = Integer.valueOf(BAYAR.getText());
            kembalian = bayar-TOTAL;
            KEMBALIAN.setText(String.valueOf(kembalian).trim());
            //         getData();
        } catch (Exception e) { 

        }
    }//GEN-LAST:event_BAYARKeyReleased
    public void getDataPembelian() {

//        pelanggan.getDataVector().removeAllElements();
//        pelanggan.fireTableDataChanged();
        try {
//membuat statemen untuk memanggil data table tabel_buku
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "Select * from pelanggan";
            ResultSet res = stat.executeQuery(sql);
//pengecekan terhadap data tabel_buku
            while (res.next()) {
                Object[] obj = new Object[3];
                obj[0] = res.getString("ID_PELANGGAN");
                obj[1] = res.getString("NAMA");
                obj[2] = res.getString("NOHP");
                pelanggan.addRow(obj);
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    public void TABELbarang() {

        mdl.getDataVector().removeAllElements();
        mdl.fireTableDataChanged();
        try {

//membuat statemen untuk memanggil data table tabel_buku
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "Select * from barangdb";
            ResultSet res = stat.executeQuery(sql);

//pengecekan terhadap data tabel_buku
            while (res.next()) {
                Object[] obj = new Object[7];
                obj[0] = res.getString("ID_BARANG");
                obj[1] = res.getString("namabarang");
                obj[2] = res.getString("jumlah");
                obj[3] = res.getString("harga");
                obj[4] = res.getString("garansi");
                obj[5] = res.getString("waktu");
                obj[6] = res.getString("keterangan");
                mdl.addRow(obj);
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

    }

//    public int CEKTOCK() throws SQLException {
//        int stok = 0;
//
//        String total = "SELECT jumlah from barangdb where ID_BARANG = '" + idbarang.getText() + "'";
//
//        try {
//            koneksi connection = new koneksi();
//            Statement stat = connection.configDB().createStatement();
//            ResultSet res = stat.executeQuery(total);
//            while (res.next()) {
//                stok = Integer.parseInt(res.getString(1));
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//            System.out.println("" + ex.getMessage());
//        }
//        return stok;
//    }
//
//    public void UPDATESTOCK(String ubah) throws SQLException {
//        koneksi connection = new koneksi();
//        Statement stat = connection.configDB().createStatement();
//
//        int stokBaru = 0;
//        int total;
//        int pilih = jTable3.getSelectedRow();
//        if (pilih == -1) {
//            return;
//        }
//        String jumlahbarang = (String) jTable3.getValueAt(pilih, 2);
//        stok.setText(jumlahbarang);
//        try {
//            if (ubah.equals("TAMBAH")) {
//                stokBaru = CEKTOCK() - Integer.parseInt(JUMLAH.getText());
//            } else if (ubah.equals("DELETE")) {
//
//                stokBaru = CEKTOCK() + jml_awal;
//                total = Integer.parseInt(stok.getText()) - jml_awal;
//            }
//            String query = "UPDATE barangdb set jumlah ='" + stokBaru + "' where id_barang = '" + idbarang.getText() + "'";
//            stat.executeUpdate(query);
//
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//            System.out.println("" + ex.getMessage());
//        }
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BAYAR;
    private javax.swing.JTextField GARANSI;
    private javax.swing.JLabel HARGA;
    private javax.swing.JTextField IDPELANGGAN;
    private javax.swing.JTextField JUMLAH;
    private javax.swing.JTextField KEMBALIAN;
    private javax.swing.JTextField KODE;
    private javax.swing.JLabel KODE1;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NAMABRANG;
    public static final javax.swing.JTextField OLEH = new javax.swing.JTextField();
    private javax.swing.JTable TABELTRANSAKSI;
    private javax.swing.JLabel TEXTKODEE;
    private com.toedter.calendar.JDateChooser WAKTU;
    private javax.swing.JTextField idbarang;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable3;
    public javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel totalharga;
    // End of variables declaration//GEN-END:variables
}
