/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reparasi;

import PENJUALAN.Barang.BARANG;
import PENJUALAN.Barang.Koneksi;
import dayattt.koneksi;
import static dayattt.koneksi.configDB;
//import reparasi.buang.MASUKAN;
import java.awt.HeadlessException;
import java.awt.TextField;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer
 */
public class REPARASI extends javax.swing.JPanel {

    private DefaultTableModel mdl;
    private Tableubah model;

    private List<uubah> ubahs;
    private uubah ubah;

    /**
     * Creates new form REPARASI
     */
    public REPARASI() {       
        initComponents();
        waktu();
        
        tampil_combo();
        mdl = new DefaultTableModel();
        jTable2.setModel(mdl);
        RADIOGRUP.add(sPROSES);
        RADIOGRUP.add(sTERIMA);
        mdl.addColumn("ID_PELANGGAN");
        mdl.addColumn("NAMA");
        mdl.addColumn("NOHP");

        getData();
        CARIData();
        model = new Tableubah();
//        TABELPELANGGAN();

        jTable1.setModel(model);

        ubahs = new ArrayList<uubah>();
        loadData();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent lse) {
                int row = jTable1.getSelectedRow();
                if (row != -1) {
                    ubah = model.get(row);
                    NAMA_PELANGGAN.setText(ubah.getNAMA());
                    idPELANGGAN.setText(ubah.getIDPELANGGAN());
                    NOSERI.setText(ubah.getNOSERI());
                    JENIS.setSelectedItem(ubah.getJENIS());
                    KELENGKAPAN.setText(ubah.getKELENGKAPAN());
                    MERK.setText(ubah.getMEREK());
                    KELUHAN.setText(ubah.getKELUHAN());
                    HARGADG.setText(ubah.getHARGADIAGNOSA());
                    APK.setText(ubah.getAPLIKASI());
                    TTLHARGAAPK.setText(ubah.getTOTALHARGAAPLIKASI());
//                    F2.STATUS.setText(ubah.getGaransi());
                    CATATAN.setText(ubah.getCATATAN());
                    WAKTU.setDate(ubah.getWAKTU());
                    HARGA.setText(ubah.getTOTALHARGA());
                    KODE.setText(ubah.getCODE());
                    USER.setText(ubah.getUSER());
                    if (ubah.getSTATUS().equalsIgnoreCase("PROSES")) {
                        sPROSES.setSelected(true);
                    } else {
                        sTERIMA.setSelected(true);
                    }

                    sTERIMA.setEnabled(true);
                    sPROSES.setEnabled(true);
                    btn_ubah.setEnabled(true);
                    btnhapus.setEnabled(true);
                }
            }

        });
    }

    public void loadData() {
        ubahs = Koneksiubah.getubahDAO().getAll();
        model.setData(ubahs);
    }

    private void clear() {

        NOSERI.setText("");
        JENIS.setSelectedIndex((0));
        KELENGKAPAN.setText("");
        MERK.setText("");
        KELUHAN.setText("");
        RADIOGRUP.clearSelection();
        CATATAN.setText("");
        WAKTU.setDate(new Date());
        HARGA.setText("");
        KODE.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private class Tableubah extends AbstractTableModel {

        private List<uubah> list = new ArrayList();

        public void setData(List<uubah> list) {
            this.list = list;
            fireTableDataChanged();
        }

        public int getRowCount() {
            return list.size();
        }

        public int getColumnCount() {
            return 16;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return list.get(rowIndex).getIDPELANGGAN();
                case 1:
                    return list.get(rowIndex).getNAMA();
                case 2:
                    return list.get(rowIndex).getNOSERI();
                case 3:
                    return list.get(rowIndex).getJENIS();
                case 4:
                    return list.get(rowIndex).getKELENGKAPAN();
                case 5:
                    return list.get(rowIndex).getMEREK();
                case 6:
                    return list.get(rowIndex).getKELUHAN();
                case 7:
                    return list.get(rowIndex).getHARGADIAGNOSA();
                case 8:
                    return list.get(rowIndex).getAPLIKASI();
                case 9:
                    return list.get(rowIndex).getTOTALHARGAAPLIKASI();
                case 10:
                    return list.get(rowIndex).getSTATUS();
                case 11:
                    return list.get(rowIndex).getCATATAN();
                case 12:
                    return list.get(rowIndex).getWAKTU();
                case 13:
                    return list.get(rowIndex).getTOTALHARGA();
                case 14:
                    return list.get(rowIndex).getCODE();
                case 15:
                    return list.get(rowIndex).getUSER();
                default:
                    return null;
            }
        }

        @Override
        public String getColumnName(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return "ID_PELANGGAN";
                case 1:
                    return "NAMA PELANGGAN";
                case 2:
                    return "NOSERI";
                case 3:
                    return "JENIS";
                case 4:
                    return "KELENGKAPAN";
                case 5:
                    return "MEREK";
                case 6:
                    return "KELUHAN";
                case 7:
                    return "HARGADIAGNOSA";
                case 8:
                    return "APLIKASI";
                case 9:
                    return "HARGAAPLIKASI";
                case 10:
                    return "STATUS";
                case 11:
                    return "CATATAN";
                case 12:
                    return "WAKTU";
                case 13:
                    return "HARGA";
                case 14:
                    return "CODE";
                case 15:
                    return "USER";
                default:
                    return null;
            }
        }

        public void insertTable(uubah ubah) {
            list.add(ubah);
            fireTableDataChanged();
        }

        public void updateTable(uubah ubah, int rowIndex) {
            list.set(rowIndex, ubah);
            fireTableDataChanged();
        }

        public uubah get(int rowIndex) {
            return list.get(rowIndex);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RADIOGRUP = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CATATAN = new javax.swing.JTextArea();
        WAKTU = new com.toedter.calendar.JDateChooser();
        HARGA = new javax.swing.JTextField();
        sPROSES = new javax.swing.JRadioButton();
        sTERIMA = new javax.swing.JRadioButton();
        KODE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        MERK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KELENGKAPAN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        KELUHAN = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        NOSERI = new javax.swing.JTextField();
        JENIS = new javax.swing.JComboBox<>();
        idPELANGGAN = new javax.swing.JTextField();
        NAMA_PELANGGAN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        APK = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        TTLHARGAAPK = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Diagnosa = new javax.swing.JComboBox<>();
        HARGADG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        CARIPELANGGAN = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 97, 56));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 97, 56));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 102));
        jScrollPane1.setForeground(new java.awt.Color(0, 255, 102));

        jTable1.setBackground(new java.awt.Color(0, 204, 204));
        jTable1.setForeground(new java.awt.Color(51, 0, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        cari.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cari.setForeground(new java.awt.Color(153, 153, 153));
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 157));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_search_32px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(190, 235, 159));
        jPanel4.setForeground(new java.awt.Color(0, 102, 0));

        jPanel5.setBackground(new java.awt.Color(190, 235, 159));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("TOTAL");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("WAKTU");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("CATATAN");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("STATUS");

        CATATAN.setColumns(20);
        CATATAN.setRows(5);
        jScrollPane2.setViewportView(CATATAN);

        WAKTU.setMaxSelectableDate(new java.util.Date(253370797281000L));

        HARGA.setEnabled(false);

        sPROSES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sPROSES.setText("PROSES");
        sPROSES.setEnabled(false);
        sPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPROSESActionPerformed(evt);
            }
        });

        sTERIMA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sTERIMA.setText("SELESAI");
        sTERIMA.setEnabled(false);
        sTERIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTERIMAActionPerformed(evt);
            }
        });

        KODE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KODEMousePressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("KODE");

        USER.setEnabled(false);
        USER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                USERMousePressed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 157));
        jButton5.setText("SIMPAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(255, 255, 157));
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 255, 157));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("PENGGUNA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(USER)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sPROSES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sTERIMA))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(KODE)
                    .addComponent(HARGA)
                    .addComponent(WAKTU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sPROSES))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sTERIMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WAKTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(HARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(190, 235, 159));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MERK");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID PELANGGAN");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("JENIS");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("KELENGKAPAN");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("KELUHAN / DIAGNOSA");

        KELUHAN.setColumns(20);
        KELUHAN.setRows(5);
        KELUHAN.setEnabled(false);
        jScrollPane3.setViewportView(KELUHAN);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("NOSERI BARANG");

        JENIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Jenis---", "Laptop", "Printer", "CPU" }));

        idPELANGGAN.setEnabled(false);
        idPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPELANGGANActionPerformed(evt);
            }
        });
        idPELANGGAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idPELANGGANKeyTyped(evt);
            }
        });

        NAMA_PELANGGAN.setEnabled(false);
        NAMA_PELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMA_PELANGGANActionPerformed(evt);
            }
        });
        NAMA_PELANGGAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NAMA_PELANGGANKeyTyped(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("APLIKASI TAMBAHAN");

        APK.setColumns(20);
        APK.setRows(5);
        jScrollPane5.setViewportView(APK);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        TTLHARGAAPK.setText("0");
        TTLHARGAAPK.setEnabled(false);
        TTLHARGAAPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTLHARGAAPKActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("JUMLAH");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("HARGA");

        Diagnosa.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosaActionPerformed(evt);
            }
        });

        HARGADG.setEnabled(false);
        HARGADG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARGADGActionPerformed(evt);
            }
        });
        HARGADG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HARGADGKeyReleased(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("HARGA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_plus_17px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("NAMA  APLIKASI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(idPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAMA_PELANGGAN))
                    .addComponent(NOSERI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JENIS, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KELENGKAPAN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MERK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HARGADG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addGap(10, 10, 10)
                                .addComponent(TTLHARGAAPK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(109, 109, 109))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NAMA_PELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOSERI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JENIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KELENGKAPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MERK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HARGADG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addComponent(Diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TTLHARGAAPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel19)))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane4.setBackground(new java.awt.Color(0, 255, 102));
        jScrollPane4.setForeground(new java.awt.Color(0, 255, 102));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jButton4.setText("PRINT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        CARIPELANGGAN.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CARIPELANGGAN.setForeground(new java.awt.Color(153, 153, 153));
        CARIPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIPELANGGANActionPerformed(evt);
            }
        });
        CARIPELANGGAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CARIPELANGGANKeyReleased(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 157));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_search_32px.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("CLEAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CARIPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CARIPELANGGAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cariKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CARIData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
if (JOptionPane.showConfirmDialog(null,"Apakah Data Telah Diisi Dengan Benar? ","Tambah Data", JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
        ubah = new uubah();
        ubah.setIDPELANGGAN(idPELANGGAN.getText());
        ubah.setNOSERI(NOSERI.getText());
        ubah.setJENIS(JENIS.getSelectedItem().toString());
        ubah.setKELANGKAPAN(KELENGKAPAN.getText());
        ubah.setMEREK(MERK.getText());
        ubah.setKELUHAN(KELUHAN.getText());
        ubah.setHARGADIAGNOSA(HARGADG.getText());
        ubah.setAPLIKASI(APK.getText());
        ubah.setTOTALHARGAAPLIKASI(TTLHARGAAPK.getText());
        //ubah.setSTATUS(.getText());
        ubah.setCATATAN(CATATAN.getText());
        ubah.setWAKTU(WAKTU.getDate());
        ubah.setTOTALHARGA(HARGA.getText());
        ubah.setCODE(KODE.getText());
        ubah.setUSER(USER.getText());
//        if (sPROSES.isSelected()){
//            ubah.setSTATUS("proses");
//        }else{
//            ubah.setSTATUS("di terima pemilik");
//        }
        Koneksiubah.getubahDAO().save(ubah);
        loadData();
        CARIData();
        clear();
        }else{
        
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if (JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin UntukMengubah Data Ini? ","Ubah Data", JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
        ubah.setIDPELANGGAN(idPELANGGAN.getText());
        ubah.setNOSERI(NOSERI.getText());
        ubah.setJENIS(JENIS.getSelectedItem().toString());
        ubah.setKELANGKAPAN(KELENGKAPAN.getText());
        ubah.setMEREK(MERK.getText());
        ubah.setKELUHAN(KELUHAN.getText());
        ubah.setHARGADIAGNOSA(HARGADG.getText());
        ubah.setAPLIKASI(APK.getText());
        ubah.setTOTALHARGAAPLIKASI(TTLHARGAAPK.getText());
        //ubah.setSTATUS(.getText());
        ubah.setCATATAN(CATATAN.getText());
        ubah.setWAKTU(WAKTU.getDate());
        ubah.setTOTALHARGA(HARGA.getText());
        ubah.setCODE(KODE.getText());
        ubah.setUSER(USER.getText());
        if (sPROSES.isSelected()) {
            ubah.setSTATUS("PROSES");
        } else {
            ubah.setSTATUS("SELESAI");
        }
        Koneksiubah.getubahDAO().update(ubah);
        loadData();
        CARIData();
        clear();
        }else{
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus Data ini?","Hapus Data", JOptionPane.YES_OPTION)==JOptionPane.YES_OPTION){
        Koneksiubah.getubahDAO().delete(ubah);
        loadData();
        clear();
        CARIData();
        }else{
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:

        int pilih = jTable2.getSelectedRow();
        if (pilih == -1) {
            return;
        }
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dMMyyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        String id = (String) jTable2.getValueAt(pilih, 0);
        idPELANGGAN.setText(id);
        KODE.setText(id + "RV" + tanggal);
        String nama = (String) jTable2.getValueAt(pilih, 1);
        NAMA_PELANGGAN.setText(nama);
        
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/datareparasi";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {

                String report = ("D:\\mencoba\\dayattt\\src\\cetak\\report1.jrxml");

                HashMap hash = new HashMap();
                //Mengambil parameter dari ireport
                hash.put("kode", KODE.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception rptexcpt) {
                System.out.println("Report Can't view because : " + rptexcpt);
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void sTERIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTERIMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTERIMAActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    private void sPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPROSESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPROSESActionPerformed

    private void KODEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KODEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KODEMousePressed

    private void CARIPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIPELANGGANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARIPELANGGANActionPerformed

    private void CARIPELANGGANKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CARIPELANGGANKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CARIPELANGGANKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        caripelanggan();
    }//GEN-LAST:event_jButton7ActionPerformed
    public void caripelanggan() {

        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID PELANGGAN");
        tabelnyo.addColumn("NAMA");
        tabelnyo.addColumn("NOHP");

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM pelanggan where ID_PELANGGAN like '%" + CARIPELANGGAN.getText() + "%' OR nama like '%" + CARIPELANGGAN.getText() + "%' OR nohp like '%" + CARIPELANGGAN.getText() + "%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),});
            }
            jTable2.setModel(tabelnyo);

        } catch (SQLException e) {
        }

    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void USERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERMousePressed

    private void NAMA_PELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMA_PELANGGANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMA_PELANGGANActionPerformed

    private void NAMA_PELANGGANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NAMA_PELANGGANKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMA_PELANGGANKeyTyped

    private void idPELANGGANKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPELANGGANKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idPELANGGANKeyTyped

    private void idPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPELANGGANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPELANGGANActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TTLHARGAAPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTLHARGAAPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTLHARGAAPKActionPerformed
public void waktu (){
Date tgl = new Date();
WAKTU.setDate(tgl);
}
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        int jumlah, harga, totalharga;
         try {
            jumlah = Integer.valueOf(jTextField1.getText());
            harga = 20000;
            totalharga = jumlah * harga;
            TTLHARGAAPK.setText(String.valueOf(totalharga));
        } catch (Exception e) {

        }
          int bayardiagnosa, TOTAL, bayarapk;

        try {
            //Kode kamu disini
            bayarapk = Integer.valueOf(HARGADG.getText());
            bayardiagnosa = Integer.valueOf(TTLHARGAAPK.getText());
            TOTAL = bayardiagnosa + bayarapk;
            HARGA.setText(String.valueOf(TOTAL).trim());
            //         getData();
        } catch (Exception e) { 

        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void HARGADGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARGADGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HARGADGActionPerformed
public void tambah (){
        String diagnosa = Diagnosa.getSelectedItem().toString();
        KELUHAN.setText(diagnosa);
    if (KELUHAN.equals("")){
        KELUHAN.setText("STILL WAITING U :)  ");
    }else{
        
    
    }

}
    private void DiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosaActionPerformed
        // TODO add your handling code here:
    dataFromDataBaseToComboBox();
     int bayardiagnosa, TOTAL, bayarapk;

        try {
            //Kode kamu disini
            bayarapk = Integer.valueOf(HARGADG.getText());
            bayardiagnosa = Integer.valueOf(TTLHARGAAPK.getText());
            TOTAL = bayardiagnosa + bayarapk;
            HARGA.setText(String.valueOf(TOTAL).trim());
            //         getData();
        } catch (Exception e) { 

        }
    }//GEN-LAST:event_DiagnosaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 int bayardiagnosa, TOTAL, bayarapk;

        try {
            //Kode kamu disini
            bayarapk = Integer.valueOf(HARGADG.getText());
            bayardiagnosa = Integer.valueOf(TTLHARGAAPK.getText());
            TOTAL = bayardiagnosa + bayarapk;
            HARGA.setText(String.valueOf(TOTAL).trim());
            //         getData();
        } catch (Exception e) { 

        }
        tambah();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void HARGADGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HARGADGKeyReleased
        // TODO add your handling code here:
           int bayardiagnosa, TOTAL, bayarapk;

        try {
            //Kode kamu disini
            bayarapk = Integer.valueOf(HARGADG.getText());
            bayardiagnosa = Integer.valueOf(TTLHARGAAPK.getText());
            TOTAL = bayardiagnosa + bayarapk;
            HARGA.setText(String.valueOf(TOTAL).trim());
            //         getData();
        } catch (Exception e) { 

        }
    }//GEN-LAST:event_HARGADGKeyReleased
    public void getData() {

        mdl.getDataVector().removeAllElements();
        mdl.fireTableDataChanged();
        try {
//membuat statemen untuk memanggil data table tabel_buku
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "Select * from pelanggan";
            ResultSet res = stat.executeQuery(sql);
//pengecekan terhadap data tabel_buku
            while (res.next()) {
                Object[] obj = new Object[3];
//                obj[0] = res.getString("ID_PEMBELIAN");
//                obj[1] = res.getString("ID_PELANGGAN");
//                obj[2] = res.getString("ID_BARANG");
                obj[0] = res.getString("ID_PELANGGAN");
                obj[1] = res.getString("NAMA");
                obj[2] = res.getString("NOHP");
                mdl.addRow(obj);
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

    }

    public void CARIData() {
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("ID_PELANGGAN");
        tabelnyo.addColumn("NAMAPELANGGAN");
        tabelnyo.addColumn("NOSERIBARNAG");
        tabelnyo.addColumn("JENIS");
        tabelnyo.addColumn("KELENGKAPAN");
        tabelnyo.addColumn("MEREK");
        tabelnyo.addColumn("KELUHAN");
        tabelnyo.addColumn("HARGADIAGNOSA");
        tabelnyo.addColumn("APLIKASI");
        tabelnyo.addColumn("HARGAAPLIKASI");
        tabelnyo.addColumn("STATUS");
        tabelnyo.addColumn("CATATAN");
        tabelnyo.addColumn("WAKTU");
        tabelnyo.addColumn("HARGA");
        tabelnyo.addColumn("CODE");
        tabelnyo.addColumn("USER");

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM masukmemasuk INNER JOIN pelanggan ON masukmemasuk.ID_PELANGGAN=pelanggan.ID_PELANGGAN where CODE like '%" + cari.getText() + "%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(2),
                    rs.getString(15),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10),
                    rs.getString(11),
                    rs.getString(12),
                    rs.getString(13),
                    rs.getString(14),
                    rs.getString(15),
                    rs.getString(16)
                });
            }
            jTable1.setModel(tabelnyo);

        } catch (Exception e) {
        }
    }

    public void tampil_combo()
    {
        koneksi connection = new koneksi();
        try {
         
            
            String sql = "select keluhan from diagnosa order by no asc";      // disini saya menampilkan NIM, anda dapat menampilkan
            Statement st = connection.configDB().createStatement();
            ResultSet res = st.executeQuery(sql);                              // yang anda ingin kan

            while (res.next()) {
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                Diagnosa.addItem((String) ob[0]);                                      // fungsi ini bertugas menampung isi dari database
            }
            res.close();
            st.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void dataFromDataBaseToComboBox(){
       
        try {
            koneksi connection = new koneksi();
            String sql = "select harga from diagnosa where keluhan='" + Diagnosa.getSelectedItem()+ "'";
            Statement st = connection.configDB().createStatement();
            ResultSet res = st.executeQuery(sql);

            while (res.next()) {
                Object[] ob = new Object[1];
                ob[0] = res.getString(1);

                HARGADG.setText((String) ob[0]);

            }
            res.close();
            st.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea APK;
    public static javax.swing.JTextField CARIPELANGGAN;
    public javax.swing.JTextArea CATATAN;
    private javax.swing.JComboBox<String> Diagnosa;
    public javax.swing.JTextField HARGA;
    private javax.swing.JTextField HARGADG;
    public static javax.swing.JComboBox<String> JENIS;
    public javax.swing.JTextField KELENGKAPAN;
    public javax.swing.JTextArea KELUHAN;
    public javax.swing.JTextField KODE;
    public javax.swing.JTextField MERK;
    public javax.swing.JTextField NAMA_PELANGGAN;
    public javax.swing.JTextField NOSERI;
    private javax.swing.ButtonGroup RADIOGRUP;
    private javax.swing.JTextField TTLHARGAAPK;
    public static final javax.swing.JTextField USER = new javax.swing.JTextField();
    public com.toedter.calendar.JDateChooser WAKTU;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btnhapus;
    public static javax.swing.JTextField cari;
    public javax.swing.JTextField idPELANGGAN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton sPROSES;
    public javax.swing.JRadioButton sTERIMA;
    // End of variables declaration//GEN-END:variables
}
