/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dayattt;

import PENJUALAN.JPENJUALAN;
import dayattt.pelaporan.JPELAPORAN;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import reparasi.REPARASI;

/**
 *
 * @author Acer
 */
public class awal extends javax.swing.JFrame {

    /**
     *
     */
    REPARASI RP;
    JPENJUALAN PJ;
    JPELAPORAN LP;
    MENUPILIHAN MP;

    public awal() {
        initComponents();

        //MASUKAN FRAME
        RP = new REPARASI();
        PJ = new JPENJUALAN();
        LP = new JPELAPORAN();
        MP = new MENUPILIHAN();

        jPanel4.add(RP);
        jPanel4.add(PJ);
        jPanel4.add(LP);
        jPanel4.add(MP);

        MP.setVisible(true);
        RP.setVisible(false);
        PJ.setVisible(false);
        LP.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_REPARASI = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTN_PENJUALAN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        BTN_MINIMIZE = new javax.swing.JLabel();
        BTN_RESTOREDOWN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_HOME.setBackground(new java.awt.Color(0, 0, 102));
        BTN_HOME.setEnabled(false);
        BTN_HOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_HOMEMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_home_page_32px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME");

        javax.swing.GroupLayout BTN_HOMELayout = new javax.swing.GroupLayout(BTN_HOME);
        BTN_HOME.setLayout(BTN_HOMELayout);
        BTN_HOMELayout.setHorizontalGroup(
            BTN_HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );
        BTN_HOMELayout.setVerticalGroup(
            BTN_HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_HOMELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BTN_HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(BTN_HOMELayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BTN_HOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        BTN_REPARASI.setBackground(new java.awt.Color(0, 0, 102));
        BTN_REPARASI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN_REPARASIMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_automatic_32px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REPARASI");

        javax.swing.GroupLayout BTN_REPARASILayout = new javax.swing.GroupLayout(BTN_REPARASI);
        BTN_REPARASI.setLayout(BTN_REPARASILayout);
        BTN_REPARASILayout.setHorizontalGroup(
            BTN_REPARASILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_REPARASILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(77, 77, 77)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
        );
        BTN_REPARASILayout.setVerticalGroup(
            BTN_REPARASILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_REPARASILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BTN_REPARASILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BTN_REPARASI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 50));

        BTN_PENJUALAN.setBackground(new java.awt.Color(0, 0, 102));
        BTN_PENJUALAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN_PENJUALANMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_online_store_32px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PENJUALAN");

        javax.swing.GroupLayout BTN_PENJUALANLayout = new javax.swing.GroupLayout(BTN_PENJUALAN);
        BTN_PENJUALAN.setLayout(BTN_PENJUALANLayout);
        BTN_PENJUALANLayout.setHorizontalGroup(
            BTN_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_PENJUALANLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(69, 69, 69)
                .addComponent(jLabel6)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        BTN_PENJUALANLayout.setVerticalGroup(
            BTN_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_PENJUALANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BTN_PENJUALANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BTN_PENJUALAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        BTN_PELAPORAN.setBackground(new java.awt.Color(0, 0, 102));
        BTN_PELAPORAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN_PELAPORANMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_report_file_32px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PELAPORAN");

        javax.swing.GroupLayout BTN_PELAPORANLayout = new javax.swing.GroupLayout(BTN_PELAPORAN);
        BTN_PELAPORAN.setLayout(BTN_PELAPORANLayout);
        BTN_PELAPORANLayout.setHorizontalGroup(
            BTN_PELAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_PELAPORANLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(69, 69, 69)
                .addComponent(jLabel8)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        BTN_PELAPORANLayout.setVerticalGroup(
            BTN_PELAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN_PELAPORANLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BTN_PELAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BTN_PELAPORAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TEKNISI KOMPUTER PONTIANAK");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 2));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 760));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 1090, 720));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        BTN_MINIMIZE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_minus_40px_1.png"))); // NOI18N
        BTN_MINIMIZE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MINIMIZEMouseClicked(evt);
            }
        });

        BTN_RESTOREDOWN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_maximize_window_40px.png"))); // NOI18N
        BTN_RESTOREDOWN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RESTOREDOWNMouseClicked(evt);
            }
        });

        BTN_TUTUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_cancel_40px.png"))); // NOI18N
        BTN_TUTUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_TUTUPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(1194, Short.MAX_VALUE)
                .addComponent(BTN_MINIMIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_RESTOREDOWN)
                .addGap(18, 18, 18)
                .addComponent(BTN_TUTUP)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_MINIMIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_TUTUP)
                        .addComponent(BTN_RESTOREDOWN)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_HOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_HOMEMouseClicked
        // TODO add your handling code here:

        setColor(BTN_HOME);
        resetColor(BTN_REPARASI);
        resetColor(BTN_PENJUALAN);
        resetColor(BTN_PELAPORAN);
//        model.setVisible(true);

        MP.setVisible(true);
        RP.setVisible(false);
        PJ.setVisible(false);
        LP.setVisible(false);
//        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_BTN_HOMEMouseClicked

    private void BTN_REPARASIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_REPARASIMousePressed
        // TODO add your handling code here:

        //PENGHILANGAN TABEL
//        model.setVisible(false);
//        jScrollPane2.setVisible(false);
        //PEMANGGILAN FRAME
        MP.setVisible(false);
        RP.setVisible(true);
        PJ.setVisible(false);
        LP.setVisible(false);
        RP.caripelanggan();

        //PERUBAHAN WARNA
        setColor(BTN_REPARASI);
        resetColor(BTN_HOME);
        resetColor(BTN_PENJUALAN);
        resetColor(BTN_PELAPORAN);
    }//GEN-LAST:event_BTN_REPARASIMousePressed

    private void BTN_PENJUALANMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_PENJUALANMousePressed
        // TODO add your handling code here:
//        model.setVisible(false);
        setColor(BTN_PENJUALAN);
        resetColor(BTN_HOME);
        resetColor(BTN_REPARASI);
        resetColor(BTN_PELAPORAN);

        MP.setVisible(false);
        RP.setVisible(false);
        PJ.setVisible(true);
        PJ.jTextField5.setText("");
        PJ.caripelanggan();
        PJ.TABELbarang();
        
        LP.setVisible(false);
//        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_BTN_PENJUALANMousePressed

    private void BTN_PELAPORANMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_PELAPORANMousePressed
        // TODO add your handling code here:

//        model.setVisible(false);
        setColor(BTN_PELAPORAN);
        resetColor(BTN_HOME);
        resetColor(BTN_REPARASI);
        resetColor(BTN_PENJUALAN);
        
//        PJ.loadData();
        MP.setVisible(false);
        RP.setVisible(false);
        LP.tampil();
        LP.tampildatapembelian();
        PJ.setVisible(false);
        LP.setVisible(true);
//        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_BTN_PELAPORANMousePressed

    private void BTN_TUTUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_TUTUPMouseClicked
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTN_TUTUPMouseClicked

    private void BTN_MINIMIZEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MINIMIZEMouseClicked
        // TODO add your handling code here
        setState(ICONIFIED);
    }//GEN-LAST:event_BTN_MINIMIZEMouseClicked

    private void BTN_RESTOREDOWNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RESTOREDOWNMouseClicked
        // TODO add your handling code here:
        if (getExtendedState() == NORMAL) {
            setExtendedState(MAXIMIZED_BOTH);
        } else {
            setExtendedState(NORMAL);
        }
    }//GEN-LAST:event_BTN_RESTOREDOWNMouseClicked

    /**
     * @param args the command line arguments
     */
    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(0, 0, 102));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JPanel BTN_HOME = new javax.swing.JPanel();
    private javax.swing.JLabel BTN_MINIMIZE;
    public static final javax.swing.JPanel BTN_PELAPORAN = new javax.swing.JPanel();
    private javax.swing.JPanel BTN_PENJUALAN;
    private javax.swing.JPanel BTN_REPARASI;
    private javax.swing.JLabel BTN_RESTOREDOWN;
    public static final javax.swing.JLabel BTN_TUTUP = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
