/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KASIR;

import LOGIN.LOGIN;
import com.toedter.calendar.JDateChooser;
import dayattt.koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Acer
 */
public class TRANSAKSI extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet res = null;
    PreparedStatement pst = null;
    LOGIN halamanlogin;
    /**
     * Creates new form TRANSAKSI
     */
    public TRANSAKSI() {
        initComponents();
        conn = koneksitransaksi.koneksi();
         dataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
     public String ambilno, ambilkode ,ambilnama , ambiltotal, ambilbayar , ambilkembalian;
     private Date ambilwaktu;
        public String getambilno(){
            return ambilno;
        }
        public String getambilkode(){
            return ambilkode;
        }
        public String getambilnama(){
            return ambilnama;
        }
        public String getambiltotal(){
            return ambiltotal;
        }
        public String getambilbayar(){
            return ambilbayar;
        }
        public String getambilkembalian(){
            return ambilkembalian;
        }
        public Date getambilwaktu(){
            return ambilwaktu;
        } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BAYARAN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        KODETRANSAKSI = new javax.swing.JTextField();
        TOTALHARGA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        KEMBALIAN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        NAMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CARI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        BTN_MINIMIZE4 = new javax.swing.JLabel();
        BTN_RESTOREDOWN = new javax.swing.JLabel();
        BTN_TUTUP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PEMBAYARAN"));

        BAYARAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BAYARANKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("BAYAR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TOTAL HARGA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("KODE TRANSAKSI");

        KODETRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KODETRANSAKSIActionPerformed(evt);
            }
        });
        KODETRANSAKSI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KODETRANSAKSIKeyPressed(evt);
            }
        });

        TOTALHARGA.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("KEMBALIAN");

        KEMBALIAN.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("WAKTU");

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        NAMA.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NAMA");

        jButton4.setText("SIMPAN");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("d-MM-yyyy");

        jButton5.setText("UBAH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("HAPUS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        USER.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("PENGGUNA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TOTALHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(KODETRANSAKSI)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(KEMBALIAN)
                                        .addComponent(BAYARAN)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(USER))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(KODETRANSAKSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOTALHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAYARAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(KEMBALIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton6)))
                .addContainerGap())
        );

        jLabel7.setBackground(new java.awt.Color(204, 0, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TRANSAKSI PEMBAYARAN REPARASI");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });
        CARI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CARIKeyPressed(evt);
            }
        });

        jButton1.setText("CARI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CARI, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CARI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 104, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 420));

        jPanel8.setBackground(new java.awt.Color(20, 63, 107));

        BTN_MINIMIZE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_minus_40px_1.png"))); // NOI18N
        BTN_MINIMIZE4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MINIMIZE4MouseClicked(evt);
            }
        });

        BTN_RESTOREDOWN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_maximize_window_40px.png"))); // NOI18N
        BTN_RESTOREDOWN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_RESTOREDOWNMouseClicked(evt);
            }
        });

        BTN_TUTUP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dayattt/ICON/icons8_cancel_40px.png"))); // NOI18N
        BTN_TUTUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_TUTUPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(899, Short.MAX_VALUE)
                .addComponent(BTN_MINIMIZE4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_RESTOREDOWN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_TUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTN_TUTUP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_MINIMIZE4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_RESTOREDOWN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1050, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KODETRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KODETRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KODETRANSAKSIActionPerformed

    private void KODETRANSAKSIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KODETRANSAKSIKeyPressed
        // TODO add your handling code here:
        getDataPembelian();
        jButton4.setEnabled(true);
    }//GEN-LAST:event_KODETRANSAKSIKeyPressed
public void Clear (){
        KODETRANSAKSI.setText("");
        NAMA.setText("");
        TOTALHARGA.setText("");
        BAYARAN.setText("");
        KEMBALIAN.setText("");
        jDateChooser1.setDate(new Date(""));
       }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed
    private void Simpan() {

        Date d = (Date) jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String waktu = sdf.format(d).toString();
        String kode = KODETRANSAKSI.getText();
        String nama = NAMA.getText();
        String total = TOTALHARGA.getText();
        String bayar = BAYARAN.getText();
        String kembalian = KEMBALIAN.getText();
        String no = ("0");
        String usr = USER.getText();

        String queryTambah = "INSERT INTO transaksibarangkeluar(NO, KODE, NAMA, TOTAL, BAYAR, KEMBALIAN, WAKTU, USER) VALUES (?,?,?,?,?,?,?,?)";
        try {
            pst = conn.prepareStatement(queryTambah);
            pst.setString(1, no);
            pst.setString(2, kode);
            pst.setString(3, nama);
            pst.setString(4, total);
            pst.setString(5, bayar);
            pst.setString(6, kembalian);
            pst.setString(7, waktu);
            pst.setString(8, usr);
            if (kode.isEmpty()|| nama.isEmpty() || bayar.isEmpty() || total.isEmpty()||kembalian.isEmpty()||waktu.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Form bayar masih kosong");
            } else {
                if (JOptionPane.showConfirmDialog(null, "Apakah Data Yang Diisi Sudah Benar?", "Tambah Data", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Tersimpan !");
                KODETRANSAKSI.setText(null);
                NAMA.setText(null);
                TOTALHARGA.setText(null);
                BAYARAN.setText(null);
                KEMBALIAN.setText(null);
                jDateChooser1.setDate(null);
               dataTable();
            }}
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "MAAF DATA TELAH TERSEDIA");
        }
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
//      USER.setText(halamanlogin.jTextField1.getText());
        Simpan();
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BTN_MINIMIZE4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MINIMIZE4MouseClicked
        // TODO add your handling code here
        setState(ICONIFIED);
    }//GEN-LAST:event_BTN_MINIMIZE4MouseClicked

    private void BTN_RESTOREDOWNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_RESTOREDOWNMouseClicked
        // TODO add your handling code here:
        if (getExtendedState() == NORMAL) {
            setExtendedState(MAXIMIZED_BOTH);
        } else {
            setExtendedState(NORMAL);
        }
    }//GEN-LAST:event_BTN_RESTOREDOWNMouseClicked

    private void BTN_TUTUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_TUTUPMouseClicked
        // TODO add your handling code here:
       int selectedOption = JOptionPane.showConfirmDialog(null,
                "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_BTN_TUTUPMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ubah();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        hapus();
        
    }//GEN-LAST:event_jButton6ActionPerformed
public void hapus(){
       String queryDelete = "DELETE FROM transaksibarangkeluar WHERE NO=?";
        int tabelData = jTable1.getSelectedRow();
        try {
            pst = conn.prepareStatement(queryDelete);
            pst.setString(1, jTable1.getValueAt(tabelData, 0).toString());
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data?", "Hapus Data", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
             pst.execute();
              JOptionPane.showMessageDialog(null, "Data Berhasil dihapus !");
                KODETRANSAKSI.setText(null);
                NAMA.setText(null);
                TOTALHARGA.setText(null);
                BAYARAN.setText(null);
                KEMBALIAN.setText(null);
                jDateChooser1.setDate(null);
             dataTable();
  }
        }
        catch (SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
}
    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        
        
//        JDateChooser JDateChooser = new JDateChooser();
//        JDateChooser.setDateFormatString("dMMyyyy");
         int pilih = jTable1.getSelectedRow();
        if (pilih == -1) {
            return;
        }

        String ngambilID = (String) jTable1.getValueAt(pilih, 1);
        KODETRANSAKSI.setText(ngambilID);
        String namaPelanggan = (String) jTable1.getValueAt(pilih, 2);
        NAMA.setText(namaPelanggan);
        String totalharga = (String) jTable1.getValueAt(pilih, 3).toString();
        TOTALHARGA.setText(totalharga);
        String BAYAR = (String) jTable1.getValueAt(pilih, 4).toString();
        BAYARAN.setText(BAYAR);
        String KEMBALIANN = (String) jTable1.getValueAt(pilih, 5).toString();
        KEMBALIAN.setText(KEMBALIANN);
        jDateChooser1.setDate((Date) jTable1.getModel().getValueAt(pilih, 6));
        String usr = (String) jTable1.getValueAt(pilih, 7).toString();
        USER.setText(usr);
    }//GEN-LAST:event_jTable1MousePressed

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARIActionPerformed

    private void CARIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CARIKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARIKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        caripelanggan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BAYARANKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BAYARANKeyReleased
        // TODO add your handling code here:

        int bayar, harga, kembalian;

        try {
            harga = Integer.valueOf(TOTALHARGA.getText());
            bayar = Integer.valueOf(BAYARAN.getText());
            kembalian = bayar - harga;
            KEMBALIAN.setText(String.valueOf(kembalian));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_BAYARANKeyReleased
 public void caripelanggan() {

        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("NO");
        tabelnyo.addColumn("KODE");
        tabelnyo.addColumn("NAMA");
        tabelnyo.addColumn("TOTAL HARGA");
        tabelnyo.addColumn("BAYAR");
        tabelnyo.addColumn("KEMBALIAN");
        tabelnyo.addColumn("WAKTU");
        tabelnyo.addColumn("USER");
        

        try {
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT * FROM transaksibarangkeluar where KODE like '%" + CARI.getText() + "%' OR NAMA like '%" + CARI.getText() +"%'";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                tabelnyo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getDate(7),
                    rs.getString(8),
                
                });
            }
            jTable1.setModel(tabelnyo);

        } catch (SQLException e) {
        }

    }
    
    public void getDataPembelian() {

        try {
//membuat statemen untuk memanggil data table tabel_buku
            koneksi connection = new koneksi();
            Statement stat = connection.configDB().createStatement();
            String sql = "SELECT masukmemasuk.ID_PELANGGAN, pelanggan.NAMA, "
                    + "SUM(masukmemasuk.HARGA) AS TOTAL FROM masukmemasuk "
                    + "LEFT JOIN pelanggan ON masukmemasuk.ID_PELANGGAN=pelanggan.ID_PELANGGAN "
                    + "WHERE (masukmemasuk.CODE ='"+KODETRANSAKSI.getText()+"' AND masukmemasuk.STATUS= 'SELESAI')";
            ResultSet rs = stat.executeQuery(sql);
//pengecekan terhadap data tabel_buku
             while(rs.next())
                {
                    NAMA.setText(rs.getString("NAMA"));
                    TOTALHARGA.setText(rs.getString("TOTAL"));
                   
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"GAGAL");
            }
        
    }

 private void dataTable(){
        try {
            String bacaSemuaData = "SELECT NO as 'No', KODE as 'KODE', NAMA as 'NAMA', TOTAL as 'TOTAL', BAYAR as 'BAYAR', KEMBALIAN as 'KEMBALIAN', WAKTU as 'WAKTU', USER as 'USER' FROM transaksibarangkeluar";
            pst = conn.prepareStatement(bacaSemuaData);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
 
 
//  public void dataTampil(){
//        KODETRANSAKSI.setText(ambilkode);
//        NAMA.setText(ambilnama);
//        TOTALHARGA.setText(ambiltotal);
//        BAYARAN.setText(ambilbayar);
//        KEMBALIAN.setText(ambilkembalian);
//        jDateChooser1.setDate(ambilwaktu);
//        
//    }
 private void ubah() {                                  
//        String no = edit_no.getText();

        int pilih = jTable1.getSelectedRow();
        Date d = (Date) jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String waktu = sdf.format(d).toString();
        String kode = KODETRANSAKSI.getText();
        String nama = NAMA.getText();
        String total = TOTALHARGA.getText();
        String bayar = BAYARAN.getText();
        String kembalian = KEMBALIAN.getText().toString();
        String USR = USER.getText();
        String no = (String) jTable1.getValueAt(pilih, 0).toString();
        String queryUpdate = "UPDATE transaksibarangkeluar SET KODE='"+kode+"',NAMA='"+nama+"',"
                + "TOTAL='"+total+"',BAYAR='"+bayar+"',KEMBALIAN='"+kembalian+"',WAKTU='"+waktu+"',USER='"+USR+"'WHERE NO='"+no+"'";
        try {
            pst = conn.prepareStatement(queryUpdate);
//            pst.setString(1, no);
//            pst.setString(2, kode);
//            pst.setString(3, nama);
//            pst.setString(4, total);
//            pst.setString(5, bayar);
//            pst.setString(6, kembalian);
//            pst.setString(7, waktu);
//            pst.setString(8, USR);
            if (nama.isEmpty() || bayar.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Form bayar masih kosong");
            } else {
                if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Mengubah Data?", "UBAH DATA", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Tersimpan !");
                KODETRANSAKSI.setText(null);
                NAMA.setText(null);
                TOTALHARGA.setText(null);
                BAYARAN.setText(null);
                KEMBALIAN.setText(null);
                jDateChooser1.setDate(null);
                dataTable();
            }}
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
 
 
 
                                         
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRANSAKSI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BAYARAN;
    private javax.swing.JLabel BTN_MINIMIZE4;
    private javax.swing.JLabel BTN_RESTOREDOWN;
    private javax.swing.JLabel BTN_TUTUP;
    private javax.swing.JTextField CARI;
    private javax.swing.JTextField KEMBALIAN;
    private javax.swing.JTextField KODETRANSAKSI;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField TOTALHARGA;
    public static final javax.swing.JTextField USER = new javax.swing.JTextField();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
